<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\TeamModule\Form\Type\Base;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use RK\TeamModule\Entity\Factory\TeamFactory;
use RK\TeamModule\Helper\ListEntriesHelper;

/**
 * Person editing form type base class.
 */
abstract class AbstractPersonType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var TeamFactory
     */
    protected $entityFactory;

    /**
     * @var ListEntriesHelper
     */
    protected $listHelper;

    /**
     * PersonType constructor.
     *
     * @param TranslatorInterface $translator    Translator service instance
     * @param TeamFactory        $entityFactory Entity factory service instance
     * @param ListEntriesHelper   $listHelper    ListEntriesHelper service instance
     */
    public function __construct(TranslatorInterface $translator, TeamFactory $entityFactory, ListEntriesHelper $listHelper)
    {
        $this->setTranslator($translator);
        $this->entityFactory = $entityFactory;
        $this->listHelper = $listHelper;
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addEntityFields($builder, $options);
        $this->addModerationFields($builder, $options);
        $this->addReturnControlField($builder, $options);
        $this->addSubmitButtons($builder, $options);

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $entity = $event->getData();
            foreach (['teamMemberImage'] as $uploadFieldName) {
                $entity[$uploadFieldName] = [
                    $uploadFieldName => $entity[$uploadFieldName] instanceof File ? $entity[$uploadFieldName]->getPathname() : null
                ];
            }
        });
        $builder->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) {
            $entity = $event->getData();
            foreach (['teamMemberImage'] as $uploadFieldName) {
                if (is_array($entity[$uploadFieldName])) {
                    $entity[$uploadFieldName] = $entity[$uploadFieldName][$uploadFieldName];
                }
            }
        });
    }

    /**
     * Adds basic entity fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addEntityFields(FormBuilderInterface $builder, array $options)
    {
        
        $builder->add('lastName', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Last name') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the last name of the person')
            ],'required' => true,
        ]);
        
        $builder->add('firstName', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('First name') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the first name of the person')
            ],'required' => false,
        ]);
        
        $builder->add('teamMemberImage', 'RK\TeamModule\Form\Type\Field\UploadType', [
            'label' => $this->__('Team member image') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('Please upload a portait formated image file.')
            ],
            'help' => $this->__('Please upload a portait formated image file.'),
            'attr' => [
                'class' => ' validate-upload',
                'title' => $this->__('Enter the team member image of the person')
            ],'required' => false,
            'entity' => $options['entity'],
            'allowed_extensions' => 'gif, jpeg, jpg, png',
            'allowed_size' => ''
        ]);
        
        $builder->add('teamMemberFunction', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Team member function') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('The function the person do have inside the team.')
            ],
            'help' => $this->__('The function the person do have inside the team.'),
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the team member function of the person')
            ],'required' => true,
        ]);
        
        $builder->add('teamMemberDescription', 'Symfony\Component\Form\Extension\Core\Type\TextareaType', [
            'label' => $this->__('Team member description') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('A description about the team member.')
            ],
            'help' => $this->__('A description about the team member.'),
            'empty_data' => '',
            'attr' => [
                'maxlength' => 5000,
                'class' => '',
                'title' => $this->__('Enter the team member description of the person')
            ],'required' => false
        ]);
        
        $builder->add('phoneNumber', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Phone number') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the phone number of the person')
            ],'required' => false,
        ]);
        
        $builder->add('mobileNumber', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Mobile number') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the mobile number of the person')
            ],'required' => false,
        ]);
        
        $builder->add('personEmailAddress', 'Symfony\Component\Form\Extension\Core\Type\EmailType', [
            'label' => $this->__('Person email address') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => ' validate-email',
                'title' => $this->__('Enter the person email address of the person')
            ],'required' => false
        ]);
        
        $builder->add('personAddress', 'Symfony\Component\Form\Extension\Core\Type\TextareaType', [
            'label' => $this->__('Person address') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 500,
                'class' => '',
                'title' => $this->__('Enter the person address of the person')
            ],'required' => false
        ]);
        
        $builder->add('registeredUser', 'RK\TeamModule\Form\Type\Field\UserType', [
            'label' => $this->__('Registered user') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('Here you can select which registered user is this person.')
            ],
            'help' => $this->__('Here you can select which registered user is this person.'),
            'empty_data' => '',
            'attr' => [
                'maxlength' => 11,
                'class' => ' validate-digits',
                'title' => $this->__('Enter the registered user of the person')
            ],'required' => false
        ]);
        
        $builder->add('filter', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Filter') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('the filter field is used for special block filtering. If you do not know anything about this please leave empty. No spaces are allowed.')
            ],
            'help' => $this->__('the filter field is used for special block filtering. If you do not know anything about this please leave empty. No spaces are allowed.'),
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => ' validate-nospace',
                'title' => $this->__('Enter the filter of the person')
            ],'required' => false,
        ]);
    }

    /**
     * Adds special fields for moderators.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addModerationFields(FormBuilderInterface $builder, array $options)
    {
        if (!$options['hasModeratePermission']) {
            return;
        }
    
        $builder->add('moderationSpecificCreator', 'RK\TeamModule\Form\Type\Field\UserType', [
            'mapped' => false,
            'label' => $this->__('Creator') . ':',
            'attr' => [
                'maxlength' => 11,
                'class' => ' validate-digits',
                'title' => $this->__('Here you can choose a user which will be set as creator')
            ],
            'empty_data' => 0,
            'required' => false,
            'help' => $this->__('Here you can choose a user which will be set as creator')
        ]);
        $builder->add('moderationSpecificCreationDate', 'RK\TeamModule\Form\Type\Field\DateTimeType', [
            'mapped' => false,
            'label' => $this->__('Creation date') . ':',
            'attr' => [
                'class' => '',
                'title' => $this->__('Here you can choose a custom creation date')
            ],
            'empty_data' => '',
            'required' => false,
            'widget' => 'single_text',
            'help' => $this->__('Here you can choose a custom creation date')
        ]);
    }

    /**
     * Adds the return control field.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addReturnControlField(FormBuilderInterface $builder, array $options)
    {
        if ($options['mode'] != 'create') {
            return;
        }
        $builder->add('repeatCreation', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
            'mapped' => false,
            'label' => $this->__('Create another item after save'),
            'required' => false
        ]);
    }

    /**
     * Adds submit buttons.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addSubmitButtons(FormBuilderInterface $builder, array $options)
    {
        foreach ($options['actions'] as $action) {
            $builder->add($action['id'], 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
                'label' => $this->__(/** @Ignore */$action['title']),
                'icon' => ($action['id'] == 'delete' ? 'fa-trash-o' : ''),
                'attr' => [
                    'class' => $action['buttonClass'],
                    'title' => $this->__(/** @Ignore */$action['description'])
                ]
            ]);
        }
        $builder->add('reset', 'Symfony\Component\Form\Extension\Core\Type\ResetType', [
            'label' => $this->__('Reset'),
            'icon' => 'fa-refresh',
            'attr' => [
                'class' => 'btn btn-default',
                'formnovalidate' => 'formnovalidate'
            ]
        ]);
        $builder->add('cancel', 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
            'label' => $this->__('Cancel'),
            'icon' => 'fa-times',
            'attr' => [
                'class' => 'btn btn-default',
                'formnovalidate' => 'formnovalidate'
            ]
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'rkteammodule_person';
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                // define class for underlying data (required for embedding forms)
                'data_class' => 'RK\TeamModule\Entity\PersonEntity',
                'empty_data' => function (FormInterface $form) {
                    return $this->entityFactory->createPerson();
                },
                'error_mapping' => [
                    'isRegisteredUserUserValid' => 'registeredUser',
                    'teamMemberImage' => 'teamMemberImage.teamMemberImage',
                ],
                'mode' => 'create',
                'actions' => [],
                'hasModeratePermission' => false,
            ])
            ->setRequired(['entity', 'mode', 'actions'])
            ->setAllowedTypes([
                'mode' => 'string',
                'actions' => 'array',
                'hasModeratePermission' => 'bool',
            ])
            ->setAllowedValues([
                'mode' => ['create', 'edit']
            ])
        ;
    }
}
