<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\TeamModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractTeamEvents
{
    /**
     * The rkteammodule.person_post_load event is thrown when persons
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\TeamModule\Event\FilterPersonEvent instance.
     *
     * @see RK\TeamModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const PERSON_POST_LOAD = 'rkteammodule.person_post_load';
    
    /**
     * The rkteammodule.person_pre_persist event is thrown before a new person
     * is created in the system.
     *
     * The event listener receives an
     * RK\TeamModule\Event\FilterPersonEvent instance.
     *
     * @see RK\TeamModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const PERSON_PRE_PERSIST = 'rkteammodule.person_pre_persist';
    
    /**
     * The rkteammodule.person_post_persist event is thrown after a new person
     * has been created in the system.
     *
     * The event listener receives an
     * RK\TeamModule\Event\FilterPersonEvent instance.
     *
     * @see RK\TeamModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const PERSON_POST_PERSIST = 'rkteammodule.person_post_persist';
    
    /**
     * The rkteammodule.person_pre_remove event is thrown before an existing person
     * is removed from the system.
     *
     * The event listener receives an
     * RK\TeamModule\Event\FilterPersonEvent instance.
     *
     * @see RK\TeamModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const PERSON_PRE_REMOVE = 'rkteammodule.person_pre_remove';
    
    /**
     * The rkteammodule.person_post_remove event is thrown after an existing person
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\TeamModule\Event\FilterPersonEvent instance.
     *
     * @see RK\TeamModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const PERSON_POST_REMOVE = 'rkteammodule.person_post_remove';
    
    /**
     * The rkteammodule.person_pre_update event is thrown before an existing person
     * is updated in the system.
     *
     * The event listener receives an
     * RK\TeamModule\Event\FilterPersonEvent instance.
     *
     * @see RK\TeamModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const PERSON_PRE_UPDATE = 'rkteammodule.person_pre_update';
    
    /**
     * The rkteammodule.person_post_update event is thrown after an existing new person
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\TeamModule\Event\FilterPersonEvent instance.
     *
     * @see RK\TeamModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const PERSON_POST_UPDATE = 'rkteammodule.person_post_update';
    
}
