<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\TeamModule\DependencyInjection;

use RK\TeamModule\DependencyInjection\Base\AbstractRKTeamExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class RKTeamExtension extends AbstractRKTeamExtension
{
    // custom enhancements can go here
}
