<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\TeamModule\Form\Handler\Person;

use RK\TeamModule\Form\Handler\Person\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the rKTeamModule_person_edit() function.
 * It aims on the person object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
