<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\TeamModule\Form\DataTransformer;

use RK\TeamModule\Form\DataTransformer\Base\AbstractUserFieldTransformer;

/**
 * User field transformer implementation class.
 *
 * This data transformer treats user fields.
 */
class UserFieldTransformer extends AbstractUserFieldTransformer
{
    // feel free to add your customisation here
}
