<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\TeamModule;

use RK\TeamModule\Base\AbstractRKTeamModule;

/**
 * Module implementation class.
 */
class RKTeamModule extends AbstractRKTeamModule
{
    // custom enhancements can go here
}
