<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\TeamModule\Form;

use RK\TeamModule\Form\Base\AbstractDeleteEntityType;

/**
 * Entity deletion form type implementation class.
 */
class DeleteEntityType extends AbstractDeleteEntityType
{
    // feel free to extend the base form type class here
}
