<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\TeamModule\Entity\Repository;

use RK\TeamModule\Entity\Repository\Base\AbstractPersonRepository;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for person entities.
 */
class PersonRepository extends AbstractPersonRepository
{
    // feel free to add your own methods here, like for example reusable DQL queries
}
