<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\TeamModule\Container;

use RK\TeamModule\Container\Base\AbstractHookContainer;

/**
 * Implementation class for hook container methods.
 */
class HookContainer extends AbstractHookContainer
{
    // feel free to add your own convenience methods here
}
