<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\TeamModule\Event;

use RK\TeamModule\Event\Base\AbstractFilterPersonEvent;

/**
 * Event implementation class for filtering person processing.
 */
class FilterPersonEvent extends AbstractFilterPersonEvent
{
    // feel free to extend the event class here
}
